[package]
name = "bix"
version = "0.1.0"
edition = "2021"
description = "bix programming language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
clap = { version = "3.1.2", features = ["derive"] }

